### ISSUE TITLE
KeyError: 'dark3'

### ISSUE THREAD

**Issue by totoadel** [jinfagang/yolov7#85]
i do traning on cutstom dataset and i got this error
```
`[07/11 22:24:10 detectron2]: Running with full config was omitted.
[07/11 22:24:10 detectron2]: Full config saved to ./output/config.yaml
[07/11 22:24:10 d2.utils.env]: Using a generated random seed 10422596
[07/11 22:24:10 d2.engine.defaults]: Auto-scaling the config to batch_size=2, learning_rate=0.0025, max_iter=720000, warmup=8000.
Traceback (most recent call last):
  File "train_ahmed.py", line 61, in <module>
    args=(args,),
  File "/content/detectron2/detectron2/engine/launch.py", line 82, in launch
    main_func(*args)
  File "train_ahmed.py", line 48, in main
    trainer = Trainer(cfg)
  File "/content/detectron2/detectron2/engine/defaults.py", line 376, in __init__
    model = self.build_model(cfg)
  File "/content/yolov7/train_det.py", line 37, in build_model
    model = build_model(cfg)
  File "/content/detectron2/detectron2/modeling/meta_arch/build.py", line 22, in build_model
    model = META_ARCH_REGISTRY.get(meta_arch)(cfg)
  File "/content/yolov7/yolov7/modeling/meta_arch/yolov7.py", line 95, in __init__
    backbone_shape = [backbone_shape[i].channels for i in self.in_features]
  File "/content/yolov7/yolov7/modeling/meta_arch/yolov7.py", line 95, in <listcomp>
    backbone_shape = [backbone_shape[i].channels for i in self.in_features]
KeyError: 'dark3'`
```

**Comment by jinfagang** [comment]
Using darknet53

**Comment by totoadel** [comment]
When I use darknet53 i got the error #86

**Comment by jinfagang** [comment]
You are not using latest code!

**Comment by totoadel** [comment]
I clone the repo inside colab

**Comment by jinfagang** [comment]
@totoadel If you look at the new code, the latest `dark53.yml` using `configs/base-YOLOv7.yaml` not lower case one. Check the head base config file path in your config file.

I suggest you start training using YOLOX head, this is now actively maintained. It's better than raw yolov3's darkness

**Comment by totoadel** [comment]
@jinfagang i use this` yolov7/configs/coco/yolox/yolox_convnext.yaml`
and i got this error

`07/12 15:50:41 detectron2]: Running with full config was omitted.
[07/12 15:50:41 detectron2]: Full config saved to output/coco_yolox_s/config.yaml
[07/12 15:50:41 d2.utils.env]: Using a generated random seed 42003333
[07/12 15:50:42 d2.engine.defaults]: Auto-scaling the config to batch_size=14, learning_rate=0.003375, max_iter=1840000, warmup=9600.
15:50:42 07.12 INFO yolox.py:65]: backboneshape: [96, 192, 384], size_divisibility: 32
Traceback (most recent call last):
  File "train_ahmed.py", line 60, in <module>
    args=(args,),
  File "/content/detectron2/detectron2/engine/launch.py", line 82, in launch
    main_func(*args)
  File "train_ahmed.py", line 47, in main
    trainer = Trainer(cfg)
  File "/content/detectron2/detectron2/engine/defaults.py", line 378, in __init__
    data_loader = self.build_train_loader(cfg)
  File "/content/yolov7/train_det.py", line 33, in build_train_loader
    return build_detection_train_loader(cfg, mapper=cls.custom_mapper)
  File "/content/detectron2/detectron2/config/config.py", line 207, in wrapped
    explicit_args = _get_args_from_config(from_config, *args, **kwargs)
  File "/content/detectron2/detectron2/config/config.py", line 245, in _get_args_from_config
    ret = from_config_func(*args, **kwargs)
  File "/content/detectron2/detectron2/data/build.py", line 350, in _train_loader_from_config
    proposal_files=cfg.DATASETS.PROPOSAL_FILES_TRAIN if cfg.MODEL.LOAD_PROPOSALS else None,
  File "/content/detectron2/detectron2/data/build.py", line 241, in get_detection_dataset_dicts
    dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in names]
  File "/content/detectron2/detectron2/data/build.py", line 241, in <listcomp>
    dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in names]
  File "/content/detectron2/detectron2/data/catalog.py", line 58, in get
    return f()
  File "/content/detectron2/detectron2/data/datasets/coco.py", line 500, in <lambda>
    DatasetCatalog.register(name, lambda: load_coco_json(json_file, image_root, name))
  File "/content/detectron2/detectron2/data/datasets/coco.py", line 76, in load_coco_json
    cat_ids = sorted(coco_api.getCatIds())
  File "/usr/local/lib/python3.7/dist-packages/pycocotools/coco.py", line 190, in getCatIds
    cats = self.dataset['categories']
KeyError: 'categories'`

**Comment by totoadel** [comment]
this is my test datasets https://github.com/matterport/Mask_RCNN/releases  the balloon

**Comment by jinfagang** [comment]
You should using standard coco. Following the coco format strictly. BTW, convent I didn't fully open source it.

**Comment by XinyiXiang** [comment]
```
MODEL:
  META_ARCHITECTURE: "YOLOV7" # default is YOLO, can be YOLOV7, YOLOX, YOLOMASK as well
  PIXEL_MEAN: [0.406, 0.485, 0.456] # same value as PP-YOLOv2, BGR order
  PIXEL_STD: [0.225, 0.229, 0.224]
  PADDED_VALUE: 114.0

DATASETS:
  TRAIN: ("seal_train",)
  TEST: ("seal_val",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  LR_SCHEDULER_NAME: "WarmupCosineLR"

INPUT:
  FORMAT: "BGR" # let's force BGR here, since our mean and std are BGR order. if PIL read it, it should convert to BGR
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  # MIN_SIZE_TEST: 608

VERSION: 2
```
I am running into the same error with above .yaml file, is this not COCO format compatible?
